os: Visual Studio 2017

init:
  # Set the AppVeyor build version number to our tag or, if untagged, to the commit hash
  # See https://github.com/appveyor/ci/issues/691
  # Also include the build number, to distinguish between rebuilds of the same commit
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME)_#$env:APPVEYOR_BUILD_NUMBER"
      } else {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.Substring(0,8))_#$env:APPVEYOR_BUILD_NUMBER"
      }

environment:
  global:
    BITS: 32
  matrix:
    - CONFIGURATION: Debug
      COMPILER: MSVC
      PLATFORM: x86_32
    - CONFIGURATION: Debug
      COMPILER: MSVC
      PLATFORM: x86_64
    - CONFIGURATION: Release
      COMPILER: MSVC
      PLATFORM: x86_32
    - CONFIGURATION: Release
      COMPILER: MSVC
      PLATFORM: x86_64
    - CONFIGURATION: Release
      COMPILER: MinGW
      PLATFORM: i686
    - CONFIGURATION: Release
      COMPILER: MinGW
      PLATFORM: x86_64

build:
  project: rufus.sln
  parallel: true
  verbosity: detailed

install:
- if [%PLATFORM%]==[x86_64] set BITS=64

build_script:
- if [%COMPILER%]==[MSVC] msbuild rufus.sln /m /p:Configuration=%CONFIGURATION%,Platform=%PLATFORM% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- if [%COMPILER%]==[MinGW] C:\msys64\usr\bin\bash -lc "export PATH=/mingw%BITS%/bin:$PATH; cd /c/projects/rufus; ./configure --build=%PLATFORM%-w64-mingw32 --host=%PLATFORM%-w64-mingw32 --disable-debug; make -j4"
